Icbench fpga test
icb-platform/pulpino pull request #18
Opened 2021-09-23 08:34 UTC by dfhappyforever

fix constraints.xdc & pulpino_wrap.sv for 64pin pulpino.

2021-09-23 10:45 UTC, hongzhi2015 requested changes

2021-09-23 10:45 UTC, hongzhi2015 commented on SIM.md
> +
Remove these 3 lines.

2021-09-23 10:45 UTC, hongzhi2015 commented on fpga/pulpino-icbv1board/rtl/pulpino_wrap.sv
> +// License, Version 0.51 (the “License�?); you may not use this file except in
Wrong character?

2021-09-23 10:45 UTC, hongzhi2015 commented on fpga/pulpino-icbv1board/rtl/pulpino_wrap.sv
> +// this License is distributed on an “AS IS�? BASIS, WITHOUT WARRANTIES OR
Wrong character?

2021-09-23 10:45 UTC, hongzhi2015 commented on fpga/pulpino-icbv1board/rtl/pulpino_wrap.sv
> +//  uart_rts,
Remove commented signals on port.

2021-09-23 10:45 UTC, hongzhi2015 commented on fpga/pulpino-icbv1board/rtl/pulpino_wrap.sv
> +  else if(counter==4'd1)
Frequency changed to 25MHz?

2021-09-24 01:54 UTC, dfhappyforever commented on fpga/pulpino-icbv1board/rtl/pulpino_wrap.sv
> +// License, Version 0.51 (the “License�?); you may not use this file except in
This paragraph exists in every document

2021-09-24 01:55 UTC, dfhappyforever commented on fpga/pulpino-icbv1board/rtl/pulpino_wrap.sv
> +// this License is distributed on an “AS IS�? BASIS, WITHOUT WARRANTIES OR
This paragraph exists in every document

2021-09-24 01:59 UTC, dfhappyforever commented on fpga/pulpino-icbv1board/rtl/pulpino_wrap.sv
> +  else if(counter==4'd1)
12.5Mhz

2021-09-24 12:14 UTC, closed without merging